### ISSUE TITLE
ES module support

### ISSUE THREAD

**Issue by controversial** [napi-rs/napi-rs#1429]
Does napi-rs support publishing a package with a generated ES-module `index.mjs` (for use with es modules) in addition to the (commonjs-based) `index.js` it currently generates?

Modern node packages often publish both forms together, like so:
```json
{
  "type": "module",
  "exports": {
    "import": "./index.mjs",
    "require": "./index.cjs",
    "types": "./index.d.ts"
  },
  "main": "./index.cjs",
  "types": "./index.d.ts"
}
```
but I’m not sure whether naps-rs supports this use case.

**Comment by Brooooooklyn** [comment]
@controversial NAPI-RS has already supported pure esm projects. You don't need to generate an `index.mjs` to support esm project, you can try to run `import { createCanvas } from '@napi-rs/canvas', it works perfectly

**Comment by controversial** [comment]
@Brooooooklyn `@napi-rs/canvas` is published as a CommonJS package, as far as I can tell—when I install @napi-rs/canvas, I get a package with an index.js using `module.exports`.

I’m interested in setting `"type": "module"` in `package.json` for the package I’m publishing.

**Comment by magiclen** [comment]
> I was able to solve my issues (once I had `"type": "module"` in package.json):
> 
>     1. Run `napi build` with `--js binding.cjs` to ensure the file napi generates is treated as a commonjs module
> 
>     2. Making an `index.js` file to `export * from './binding.cjs';`

This solution works. But I don't like to use the `--platform` option because it generates so much code.

Assume `index.node` only has 2 functions `f1` and `f2`. I wish there is a way that `napi build` can generate a JS file (`index.cjs`) like below,

```typescript
/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { f1, f2 } = require('./index.node')

module.exports.f1 = f1
module.exports.f2 = f2
```

Because it seems that we cannot load `index.node` via the `import ... from`  statement. The following code will not work,

```typescript
import {f1} from './index.node'
```

**Comment by jcbhmr** [comment]
I'd be interested in seeing **codegen support** for ESM so that you can use async file stuff instead of `existsSync()` and `readFileSync()` since ESM supports top-level await. This way, I could lazily `import("my-math-computing-napi-package-that-i-use-in-an-http-endpoint")` while serving HTTP requests and expect it to **not** cause a half-second pause do to synchronous CJS stuff.

Right now, I have to manually re-create the index.js as ESM to avoid all the synchronous `execSync()` and `require()` calls that the default index.js file does when initially loaded.

**Comment by jjangga0214** [comment]
> 1. Run `napi build` with `--js binding.cjs` to ensure the file napi generates is treated as a commonjs module

with `--dts` option as well unless you don't want napi-rs to generate typing.

```
napi build --js binding.cjs --dts binding.d.ts
```
