### ISSUE TITLE
Segmentation fault when trying to use `set_len` on `Vec<Buffer>` or `Vec<String>`

### ISSUE THREAD

**Issue by magiclen** [napi-rs/napi-rs#1570]
**src/lib.js**

```rust
use napi::bindgen_prelude::*;
use napi_derive::napi;

#[napi]
fn f() {
    let mut v: Vec<Buffer> = Vec::with_capacity(20);

    unsafe {
        v.set_len(5);
    }

    println!("Hello world!");

    for i in 0..5 {
        v[i] = Buffer::from(Vec::new());
    }
}
```

**index.js**

```javascript
require("./index.node").f();
```

*Output*

```
Hello world!
[1]    124878 segmentation fault (core dumped)  node index.js
```

Environment:
* OS: Linux Mint 21.1 x86_64
* Rust: 1.68.2
* Node.js: 18.16.0
* napi: 2.12.5

The segmentation fault happens when `v` is dropping. The code below doesn't show segmentation fault,

```rust
use napi::bindgen_prelude::*;
use napi_derive::napi;

#[napi]
fn f() {
    let mut v: Vec<Buffer> = Vec::with_capacity(20);

    unsafe {
        v.set_len(5);
    }

    println!("Hello world!");

    for i in 0..5 {
        v[i] = Buffer::from(Vec::new());
    }

    std::mem::forget(v);
}
```

**Comment by magiclen** [comment]
A more weird thing is if we use `spare_capacity_mut` to set `Buffer`s, the segmentation fault is gone

```rust
use napi::bindgen_prelude::*;
use napi_derive::napi;

#[napi]
fn f() {
    let mut v: Vec<Buffer> = Vec::with_capacity(20);

    let a = v.spare_capacity_mut();

    for i in 0..5 {
        a[i].write(Buffer::from(Vec::new()));
    }

    unsafe {
        v.set_len(5);
    }

    println!("Hello world!");
}
```

**Comment by axnsan12** [comment]
The first version is undefined behavior.

> [Safety](https://doc.rust-lang.org/beta/std/vec/struct.Vec.html#safety-2)
> ...
> The elements at old_len..new_len **must be initialized**.

Calling `set_len` with a length greater than the current length will assert that all Vec elements up to that point are initialized (which, in your first example, they aren't). Later, assigning to `v[i]` will attempt to drop the old, unitialized value at `v[i]`.

It is not weird that using `spare_capacity_mut` doesn't crash, since that usage is sound and is the proper way to do what you are showing.
