### ISSUE TITLE
CLI does not support versions like alpha

### ISSUE THREAD

**Issue by kdy1** [napi-rs/napi-rs#174]
I tried to publish `@swc/core@v1.2.27-alpha.1`, which should publish `@swc/core-*@v1.2.27`, but npm script published `@swc/core-*@v1.2.27`

**Comment by Brooooooklyn** [comment]
Because CLI could not find any version information from `commit log` nor `package.json`, I added `RELEASE_VERSION` env support in `0.3.8`. So we can set `RELEASE_VERSION` from `${{ GITHUB_REF#refs/*/ }}`: https://github.com/swc-project/swc/pull/1073/files#diff-963196a76268651f2135d3bbebba60faR131-R132
