### ISSUE TITLE
Memory leak in `Reference.share_with`

### ISSUE THREAD

**Issue by lbarthon** [napi-rs/napi-rs#1952]
Hey team! Over the past couple days, we noticed a small memory leak in one of our applications, as we enabled a new feature. It was very subtle, but memory usage increased slowly over the hours, quickly reaching our memory limit, which then caused our service to be OOM killed.

This new feature relies on `napi-rs` (love it ❤️ ). It isn't the first time we use it on that specific app, but it's the first time that we use both `Reference` and `SharedReference`, as the types we needed to expose required lifetimes.

From the investigation we conducted, using `SharedReference` lead to a leak of 32 bytes every time we used it. I made a little reproduction available at https://github.com/lbarthon/napi-leak.

My understanding is that the `Reference.share_with` method explicitly leaks memory with `Box::leak`, and then the memory should be freed later on in the drop. When debugging, I added logs in a couple places, and it seemed that the drop was never called - https://github.com/napi-rs/napi-rs/blob/main/crates/napi/src/bindgen_runtime/js_values/value_ref.rs#L140-L143
Also worth noting that when I commented the whole logic around `finalize_callbacks`, the leak was still there, and it didn't make anything worse.

I reproduced this on an arm64 MacOS machine, running NodeJS 20.11.1 (latest LTS). Given the memory usage we saw on Linux, it should be reproducible on it too.

I would happily send a PR with a patch, but my knowledge of napi & napi-rs is way too little to do so, efficiently. I hope we'll find a solution to that!

**Comment by Brooooooklyn** [comment]
Hey @lbarthon; I've submitted a fix for a potential memory leak scenario. But there are a few points that need to be clarified: In this line, the `a` instance is declared as a global variable, which means it will never be gc by the vm: https://github.com/lbarthon/napi-leak/blob/d10409447abf1ff8d20b30eeb944927b0049f17f/run_leak.js#L2.
And then, this line pushes the `b` instance into a global Array, which means the allocated `b` will never be gc either: https://github.com/lbarthon/napi-leak/blob/main/run_leak.js#L8

> Also worth noting that when I commented the whole logic around finalize_callbacks, the leak was still there, and it didn't make anything worse.

This is the actual bug I fixed; it only occurs when the `#[napi]` derived struct contains the zero field, in this case, the allocated memory address for `Box::into_raw(Box::new(A))` is always `0x1`; so that every new created class instance will overwrite the previous `finalize_callbacks` stores in `REFERENCE_MAP`

**Comment by lbarthon** [comment]
Hey @Brooooooklyn! Thanks for looking into that so promptly.

I updated the repro linked above, as it seems that for you `b` was global and would never be GC'd. I put everything in a separate scope, and called the GC outside of it. This should ensure that the variables get collected, am I right?

Also, the problem we have in production is not with an empty struct, I just made it empty for the repro, as I thought it'd be simpler, and not misleading. If you update my repro and add a field to `A`, it will still break, whether this one is exposed to napi (`pub`) or not.

The same code still leaks 32 bytes per `Reference.share_with` call for empty and non-empty structs, I'm wondering if the `leaks` tool I use on MacOS has a problem understanding if we kept the reference to the memory or not, and just marks it as leaked as it's not understanding what happens.

Note: I created https://github.com/napi-rs/napi-rs/issues/1959 as I initially found a problem with `constructors` after bumping napi to 2.15.2, happy to track subsequent problems here if you see a better fit.
