### ISSUE TITLE
Feature Request: Support generation of string literal union from Rust enums

### ISSUE THREAD

**Issue by inokawa** [napi-rs/napi-rs#2021]
I'm using a module generated by napi-rs in Next.js App Router. In TypeScript with `isolatedModules: true`(it's default in Next.js) or `verbatimModuleSyntax: true`, importing const enums can cause errors.

We can generate enum with `--no-const-enum` option to avoid the errors. However enum is not zero bundle size like const enum. Generating literal union would be better in some situation.

graphql-codegen has `enumsAsTypes` option for the similar purpose.
https://the-guild.dev/graphql/codegen/plugins/typescript/typescript#enumsastypes
A PR with similar motivation.
https://github.com/aurelia/aurelia/pull/1870

**Comment by Brooooooklyn** [comment]
I currently don't have time to deal with this issue. If anyone wants to help implement this feature, I have some initial ideas here.

We already support the `string_enum` in `#[napi]` macro: https://github.com/napi-rs/napi-rs/blob/main/examples/napi/src/enum.rs#L23, the things we need to do to support this feature is change the generated types for the `--no-const-enum` enums. Because the `#[napi] enum` in Rust actually doesn't match the behavior of no-const `enum` in TypeScript. So we need to change the generated types for `--no-const-enum` enums like:

```ts
export const StringEnum = {
  a: 'a',
  b: 'b',
  c: 'c',
} as const
export type StringEnumType = (typeof StringEnum)[keyof typeof StringEnum]

export function acceptStringEnum(arg: StringEnumType)
```
