### ISSUE TITLE
Inspiration for napi-rs

### ISSUE THREAD

**Issue by mattcollier** [napi-rs/napi-rs#367]
Is there a blog post or the like that describes the inspiration for this project? I read much of what is currently available at https://napi.rs/ and did not find what I'm looking for. I gather that `neon` is the incumbent in this space. I'm interested in know how this project hopes to distinguish itself from other projects in the space.

I'm evaluating my options for building N-API add-ons for Nodejs in Rust, why would/should one choose `napi-rs` over `neon`?

**Comment by Brooooooklyn** [comment]
hmmm, documents and articles is still in developing for now in https://napi.rs

When this project started, neon had no plans for N-API, and at that time some of my projects needed N-API support. Now that the N-API support in neon is almost complete, napi-rs will not be very different from neon in terms of N-API support.
On the other hand, neon lacks a good release management tool, which is crucial for authors writing native addon.

> I'm interested in know how this project hopes to distinguish itself from other projects in the space.

I will write articles to introduce the differences between neon and napi-rs.

**Comment by adumbidiot** [comment]
One of the ways this library distinguishes itself from `neon` is the interface. `neon` has 2 backends: a v8 backend and an incomplete napi backend. napi is better since its abi stable. Lots of napi stuff in `neon` doesn't work last I checked like stuff needed for threadsafe callbacks. I personally feel like `napi` is also a simpler, lighter weight abstraction than `neon` since it doesn't try to abstract over 2 different apis.
