### ISSUE TITLE
Memory leak in `from_js_value` function

### ISSUE THREAD

**Issue by Brooooooklyn** [napi-rs/napi-rs#583]
See https://github.com/napi-rs/napi-rs/issues/581 for context

**Comment by pimeys** [comment]
Thanks for reacting fast to these.

I'm thinking that maybe it would be good to have tests detecting leak regressions. You can't really trust the v8 data you get from node, but something like running 1000 function calls, then seeing the resident set size before and after using tools like `ps` to detect leaks.

We're probably introducing similar tests in Prisma, but would make sense to catch the regressions already in here, due to Prisma introspection tests having a delay of multiple days (Rust stuff gets merged, the introspection tests queued up and then a JS engineer pings me in Slack about the regression)...

**Comment by Brooooooklyn** [comment]
I think testing this scenario in Docker is not complex, there are many restful API existed for inspect resources usage for Docker, and there is https://github.com/apocas/dockerode for calling these apis in Node.js.

 I will try to implement a simple ***memory leak regressions***  stage in CI, using the Docker API provided in Github actions.
