### ISSUE TITLE
CLI complains "Cannot read property 'split' of undefined" when publishing

### ISSUE THREAD

**Issue by huming2207** [napi-rs/napi-rs#600]
Hi @Brooooooklyn ,

Firstly, great thanks for your work on this project!

Right now I am trying to publish my project. The repo is here: https://github.com/huming2207/plunger-binding

I think I have encountered a problem. Somehow `napi prepublish -t npm` throws this error:

```
Type Error: Cannot read property 'split' of undefined
    at PrePublishCommand.<anonymous> (/home/hu/Projects/plunger-binding/node_modules/@napi-rs/cli/scripts/pre-publish.js:76:65)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hu/Projects/plunger-binding/node_modules/tslib/tslib.js:114:62)
```

The CLI's version is the latest 1.0.4. I've tried running `napi prepublish -t npm` or `npm publish`, but both of them generate the same result. Have I misused it or is this a bug?

Regards,
Jackson

**Comment by huming2207** [comment]
Also, could you please consider briefly updating [napi.rs](napi.rs) documentation about how to publish the library? I've followed this link: https://napi.rs/recipes/publish-package but apparently it goes to nowhere.

**Comment by Brooooooklyn** [comment]
I've checked the latest config in https://github.com/huming2207/plunger-binding, the only problem is you've not **tag** the release commit you pushed, you can try `npm version [patch|minor|major]` in your next release.
And I see the https://www.npmjs.com/package/plunger-binding-linux-x64-gnu was published successed, the error log was just because ***Upload to github release failed***.

> Also, could you please consider briefly updating napi.rs documentation about how to publish the library? I've followed this link: https://napi.rs/recipes/publish-package but apparently it goes to nowhere.

Good catch, I will finish this chapter in next week.

**Comment by huming2207** [comment]
Hi @Brooooooklyn 

> I've checked the latest config in https://github.com/huming2207/plunger-binding, the only problem is you've not tag the release commit you pushed, you can try npm version [patch|minor|major] in your next release.
And I see the https://www.npmjs.com/package/plunger-binding-linux-x64-gnu was published successed, the error log was just because Upload to github release failed.

Thanks for your reply. Sorry I forgot to clarify earlier. Initially, I ran that command locally on my machine, and it kept failing with `Cannot read property 'split' of undefined`. 

Then later last night before sleep, I've just realised there's a GitHub Action CI script so I tried out the CI instead. It works fine with CI, but of course, 1. it failed to upload to GitHub release; 2. failed to compile for Linux aarch64/armv7 and macOS targets due to lack of `libusb` for `probe-rs`.

By the way, is there any way to make `npm publish` and `napi prepublish` run locally on my own machine? The reason is that we have some proprietary projects that use our self-hosted GitLab or even SVN. We cannot use GitHub Action and some of those projects do not have any CI stuff.

Regards,
Jackson

**Comment by Brooooooklyn** [comment]
Oh the `napi prepublish` is designed to run in `Github actions`, because the it was designed to publish `cross compiled binary`, and cross compile is hard really hard in local, I should documented that.

> The reason is that we have some proprietary projects that use our self-hosted GitLab or even SVN. We cannot use GitHub Action and some of those projects do not have any CI stuff.

If you really want to publish packages in local, I will add a cli flag `--skip-gh-release` to skip to upload binaries to Github releases, which could solve the `Cannot read property 'split' of undefined` problem.
