### ISSUE TITLE
I can't use argument passed to ThreadsafeFunction after calling it

### ISSUE THREAD

**Issue by kdy1** [napi-rs/napi-rs#630]
I'm actually trying to use babel plugins with swc.
But I found that I can't use the value passed to `ThreadSafeFunction`

(Similar to https://github.com/napi-rs/napi-rs/issues/436)

**Comment by Brooooooklyn** [comment]
`ThreadSafeFunction` is different to `JsFunction`, the arguments passed into `JsFunction` is `JsValue` which lifetime is managed by JavaScript engine. In the other words, the values passed into `JsFunction` will not be dropped out of the rust function scope.
But values which passed into `ThreadSafeFunction` is native rust value, it's make non sense passed a reference into `ThreadSafeFunction`, because the `call_js_back` under the hood will not be executed immediately. So `call_js_back` under the hood will not retrieved the value if passed a reference in the stack into `call` method.

I think you can pass `Rc` into `call` method in you scenario if you want access it later.

**Comment by kdy1** [comment]
Oh, you are right.
Thanks a lot!

**Comment by kdy1** [comment]
Is there a way to run some code after js function is finished?
I want to change the value in mutex to indicate the task is done.



In example of https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe_function.md#example ,


```cpp
    auto callback = []( Napi::Env env, Function jsCallback, int* value ) {
      // Transform native data into JS data, passing it to the provided
      // `jsCallback` -- the TSFN's JavaScript function.
      jsCallback.Call( {Number::New( env, *value )} );

      // >>>>> 

      // We're finished with the data.
      delete value;
    };
```


I want to execute my code at the time I marked with `>>>>>`.

**Comment by Brooooooklyn** [comment]
> I want to change the value in mutex to indicate the task is done.

A simple idea:

```rust
let is_done = AtomicBool::new(false);
let is_done_ref = &is_done;

let tsfn = ctx.env.create_threadsafe_function(&callback, 0, |cx: ThreadSafeCallContext<...>| {
  ...
  is_done_ref.store(true, Ordering::Release);
  result
})?;
```

**Comment by kdy1** [comment]
Wow, it's a clever solution. Thanks!
I think it's enough to build a request-response system.
