### ISSUE TITLE
js callback lifetime

### ISSUE THREAD

**Issue by mycrl** [napi-rs/napi-rs#872]
```rust
#[napi(object)]
#[derive(Serialize, Deserialize)]
pub struct Auth {
    pub password: String,
    pub group: u32,
}

#[napi]
pub struct A {
    callback: Box<dyn Fn() -> napi::Result<Promise<Auth>>>
}

#[napi]
impl A {

    #[napi(constructor)]
    pub fn new<C: Fn() -> napi::Result<Promise<Auth>>>(callback: C) -> Self {
        Self {
            callback: Box::new(callback)
        }
    }
}
```

Can the callback pass by js allow me to overwrite it as `static`, because calling the callback multiple times is a very real requirement, or my implementation is not good, and there is a more ideal way to write it?

**Comment by Brooooooklyn** [comment]
callback need stay in the function scope because two reason:

1. call the JavaScript callback need `napi_env`, which could only access in `#[napi] fn`
2. JavaScript function may be recycled by the JavaScript GC.

If you really want presist a callback in your program, you need `https://docs.rs/napi/1.7.11/napi/struct.Env.html#method.create_reference` for `JsFunction` :

```rust
pub fn new (env: Env, cb: JsFunction) -> Result<Self> {
  Ok(Self { callback: env.create_reference(cb)? })
}
```

And if you want to call it after it  was presisted, you need `unwrap` it from `Env`:


```rust
#[napi]
fn call_js_back(&self, env: Env) -> Result<()> {
  let js_cb: &JsFunction = env.get_reference_value(&self.callback)?;
  js_cb.call(None, &[...])?;
  Ok(())
}
```

`Env` could only be retrieved on the main thread. If you want call the presisted function in the other thread, you should use `ThreadSafeFunction`.

**Comment by mycrl** [comment]
> 

I found that `ThreadSafeFunction` can't get the returned data. Is it for any reason?

My current requirement is to let js pass a callback function to rust, which is similar to `Fn(A) -> Promise<B>`, which can be called multiple times and can be passed between multiple threads. I don't hate using `unsafe`, is there any good way at the moment?

**Comment by Brooooooklyn** [comment]
https://nodejs.org/api/n-api.html#napi_call_threadsafe_function Node-API doesn't output the `return value` after `ThreadSafeFunction` was called.

Does this example covered your scenario: https://github.com/napi-rs/napi-rs/blob/b9f43455f07fdc71006865e2b1a865e6347e5eda/examples/napi/src/threadsafe_function.rs#L8-L21 ?

**Comment by mycrl** [comment]
> https://nodejs.org/api/n-api.html#napi_call_threadsafe_function Node-API doesn't output the `return value` after `ThreadSafeFunction` was called.
> 
> Does this example covered your scenario:
> 
> https://github.com/napi-rs/napi-rs/blob/b9f43455f07fdc71006865e2b1a865e6347e5eda/examples/napi/src/threadsafe_function.rs#L8-L21
> 
> ?

Looks not what I want, but thank you for your help anyway!
